### ISSUE TITLE
Conflict from the environment.

### ISSUE THREAD

**Issue by jarvishou829** [fudan-zvg/DeepInteraction#11]
Thanks for your great work. But when I prepare the environment following the `install.md` error happens. First, the title mismatch with the command in the` install.md` to install `mmcv-full`. One is `1.4.1` and the other `1.3.18`. What's more, the numpy and ypy-websocket version conflict when installing `mmdet3d 0.17.1`. After I manage these problems, when I run the train command, the error goes behind. It seems the mismatch of pytorch and mmcv version according to [](https://blog.csdn.net/weixin_42130300/article/details/121616567). Hope you can provide some advice. Thanks.

![image](https://user-images.githubusercontent.com/35294536/205472678-ffb88246-d8cd-4f7d-9212-777cee7ede23.png)

**Comment by Alexander0Yang** [comment]
> One is `1.4.1` and the other `1.3.18`.

My typo. The version of `mmcv-full` should be `1.3.18`. I have corrected it in the `install.md`.

> What's more, the numpy and ypy-websocket version conflict when installing `mmdet3d 0.17.1`.

I remember that the `mmdet3d 0.17.1` requires `numpy < 1.20.0`. If the `numpy` installed in the previous steps is higher than this, you can manually run `pip install -r requirements/runtime.txt` to obtain the dependency with compatible version.

> After I manage these problems, when I run the train command, the error goes behind.

Seems the `mmcv` is not installed successfully. Can you run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here?

**Comment by jarvishou829** [comment]
> > One is `1.4.1` and the other `1.3.18`.
> 
> My typo. The version of `mmcv-full` should be `1.3.18`. I have corrected it in the `install.md`.
> 
> > What's more, the numpy and ypy-websocket version conflict when installing `mmdet3d 0.17.1`.
> 
> I remember that the `mmdet3d 0.17.1` requires `numpy < 1.20.0`. If the `numpy` installed in the previous steps is higher than this, you can manually run `pip install -r requirements/runtime.txt` to obtain the dependency with compatible version.
> 
> > After I manage these problems, when I run the train command, the error goes behind.
> 
> Seems the `mmcv` is not installed successfully. Can you run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here?

The collect_env.py reports the same error. By the way, I'm not sure if there's a problem with the python version. Your suggestion is 3.7, but when I install mmde3d 0.17.1, it requires 3.8 at least so I upgrade it. May be I have to try re-create a conda environment.
![image](https://user-images.githubusercontent.com/35294536/205490796-0ca12383-8b12-4df7-87ed-bb071154fb8c.png)

**Comment by Alexander0Yang** [comment]
> when I install mmde3d 0.17.1, it requires 3.8 at least so I upgrade it.

As far as I know, mmdet3d 0.17.1 is compatible with python 3.7. 

> After I manage these problems,

May I ask how you manage these problems. It does seem that the mmcv was not built correctly.

Anyway, you can feel at ease to install the environment using the recommended version of each library.

**Comment by jarvishou829** [comment]
> python mmdet3d/utils/collect_env.py

Thanks for your kind reply. I create a new environment and strictly follows the `install.md`, but errors still appear. As you can see, my env is below.
![env](https://user-images.githubusercontent.com/35294536/205632879-98f84c6c-9a41-4d79-81f4-84ad3941ce96.png)
I follow your commands to install mmcv 1.3.18, mmdet 2.14.0, mmseg 0.14.1. But when I compile `python setup.py install` to install mmdet3d 0.17.1. The error appears
![error1](https://user-images.githubusercontent.com/35294536/205633384-16e53704-67fd-4f59-bed0-bb71b49d14a6.png)
It seems the problem of scipy version. So I try to run `pip install -r requirements.ttxt`. After that I compile `python setup.py install`, no error appears. However, when I try to train, The same error goes.
![final_error](https://user-images.githubusercontent.com/35294536/205635097-1edf84b8-447d-4a92-864a-f71c10c53a47.png)

**Comment by loongofqiao** [comment]
> > python mmdet3d/utils/collect_env.py
> 
> Thanks for your kind reply. I create a new environment and strictly follows the `install.md`, but errors still appear. As you can see, my env is below. ![env](https://user-images.githubusercontent.com/35294536/205632879-98f84c6c-9a41-4d79-81f4-84ad3941ce96.png) I follow your commands to install `mmcv 1.3.18, mmdet 2.14.0, mmseg 0.14.1`. But when I compile `python setup.py install` to install mmdet3d 0.17.1. The error appears ![error1](https://user-images.githubusercontent.com/35294536/205633384-16e53704-67fd-4f59-bed0-bb71b49d14a6.png) It seems the problem of scipy version. So I try to run `pip install -r requirements.ttxt`. After that I compile `python setup.py install`, no error appears. However, when I try to train, The same error goes. ![final_error](https://user-images.githubusercontent.com/35294536/205635097-1edf84b8-447d-4a92-864a-f71c10c53a47.png) Would you please double check the `mmlab` packages version in your environment?

Same error，i also strictly follows the install.md

**Comment by Alexander0Yang** [comment]
Here is the environment we used.
```
TorchVision: 0.10.1+cu111
OpenCV: 4.5.5
MMCV: 1.3.18
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.1+f110797
```

This problem may be because the inconsistence between the environments where mmcv is built by and running on, as is suggested in the [faq doc](https://github.com/open-mmlab/mmcv/blob/master/docs/en/faq.md).

Can you run `python -c 'import mmcv; import mmcv.ops'` to check whether mmcv is correctly installed?

If the same error occurs again, you can try to recompile mmcv-full by running `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`

**Comment by loongofqiao** [comment]
> 

Thank you very much for your reply, I have solved the problem, according to your method; the test result of pretrained model should be right;
![企业微信截图_16702940344160](https://user-images.githubusercontent.com/37148936/205794714-527770bf-9cbf-498b-b076-bdca6087a514.png)
 I would like to know how to visualize the results of multi-modality, such as visualizing the 3D box result of point cloud and image frame on the nuscene ? I know mmdet3d can visualize the results of multi-modality in kitti dataset。

**Comment by jarvishou829** [comment]
> Here is the environment we used.
> 
> ```
> TorchVision: 0.10.1+cu111
> OpenCV: 4.5.5
> MMCV: 1.3.18
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: 11.1
> MMDetection: 2.14.0
> MMSegmentation: 0.14.1
> MMDetection3D: 0.17.1+f110797
> ```
> 
> This problem may be because the inconsistence between the environments where mmcv is built by and running on, as is suggested in the [faq doc](https://github.com/open-mmlab/mmcv/blob/master/docs/en/faq.md).
> 
> Can you run `python -c 'import mmcv; import mmcv.ops'` to check whether mmcv is correctly installed?
> 
> If the same error occurs again, you can try to recompile mmcv-full by running `pip install mmcv-full==1.3.18 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`

I think I address this problem. I solved this by installing `mmcv-full`, 'mmdet', 'mmsegmentation' using the officially suggested `openmim` instead of `pip`. Nothing else is changed, so I think it may be the `pip` installation problem, and I suggest the `mim` commands. @loongofqiao 
```
pip install -U openmim
mim install mmcv-full==1.3.18
mim install mmdet==2.14.0
mim install mmsegmentation==0.14.1
```
Now my env is
```
TorchVision: 0.10.1+cu111
OpenCV: 4.6.0
MMCV: 1.3.18
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.1+
```

**Comment by loongofqiao** [comment]
> > Here is the environment we used.
> > ```
> > TorchVision: 0.10.1+cu111
> > OpenCV: 4.5.5
> > MMCV: 1.3.18
> > MMCV Compiler: GCC 7.3
> > MMCV CUDA Compiler: 11.1
> > MMDetection: 2.14.0
> > MMSegmentation: 0.14.1
> > MMDetection3D: 0.17.1+f110797
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This problem may be because the inconsistence between the environments where mmcv is built by and running on, as is suggested in the [faq doc](https://github.com/open-mmlab/mmcv/blob/master/docs/en/faq.md).
> > Can you run `python -c 'import mmcv; import mmcv.ops'` to check whether mmcv is correctly installed?
> > If the same error occurs again, you can try to recompile mmcv-full by running `pip install mmcv-full==1.3.18 -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.9.0/index.html`
> 
> I think I address this problem. I solved this by installing `mmcv-full`, 'mmdet', 'mmsegmentation' using the officially suggested `openmim` instead of `pip`. Nothing else is changed, so I think it may be the `pip` installation problem, and I suggest the `mim` commands. @loongofqiao
> 
> ```
> pip install -U openmim
> mim install mmcv-full==1.3.18
> mim install mmdet==2.14.0
> mim install mmsegmentation==0.14.1
> ```
> 
> Now my env is
> 
> ```
> TorchVision: 0.10.1+cu111
> OpenCV: 4.6.0
> MMCV: 1.3.18
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: 11.1
> MMDetection: 2.14.0
> MMSegmentation: 0.14.1
> MMDetection3D: 0.17.1+
> ```

ok，Thank you

**Comment by loongofqiao** [comment]
> Here is the environment we used.
> 
> ```
> TorchVision: 0.10.1+cu111
> OpenCV: 4.5.5
> MMCV: 1.3.18
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: 11.1
> MMDetection: 2.14.0
> MMSegmentation: 0.14.1
> MMDetection3D: 0.17.1+f110797
> ```
> 
> This problem may be because the **inconsistence** between the environments where mmcv is **built by** and **running on**, as is suggested in the [faq doc](https://github.com/open-mmlab/mmcv/blob/master/docs/en/faq.md).
> 
> Can you run `python -c 'import mmcv; import mmcv.ops'` to check whether your mmcv is correctly installed?

Thank you very much for your reply, I have solved the problem, according to your method; the test result should be right;
![企业微信截图_16702940344160](https://user-images.githubusercontent.com/37148936/205796319-8e1ec9ea-74b0-4cb7-8b14-d81eff76eeb5.png)
 I would like to know how to visualize the results of multi-modality, such as visualizing the 3D box of point cloud and picture frame on the nuscene? I know mmdet3d can visualize the results of multi-modality in kitti.

**Comment by Alexander0Yang** [comment]
Hi, @sunnyHelen 
You can run `pip install -r requirements.txt` before `python setup.py install`.
Please refer to @jarvishou829‘s solution.
> It seems the problem of scipy version. So I try to run pip install -r requirements.ttxt. After that I compile python setup.py install, no error appears.

**Comment by sunnyHelen** [comment]
Thanks for your reply. Now the mmdet3d seems built successfully, but there's another error.
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/28101548/207071927-afe2eeb8-b3d4-44e0-89d2-3e0e4060bd78.png">

**Comment by Alexander0Yang** [comment]
That’s because your mmcv was not installed successfully. 
You can try to reinstall it by running `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.10.0/index.html`.

**Comment by sunnyHelen** [comment]
Yeah, problem fixed. I didn't work because I didn't uninstall the wrong version. Now the environment issue is addressed. Thank you very much.
